- client/src/app/pages/dashboard/maps/upload-form/map-upload-form.component.ts
Closes #362
The given zone file already had the properties key inside of it, so not accessing it was causing it to embed another properties key inside of it.
> Fix zone properties improperly saving

- client/src/app/pages/main/about/about.component.html
- client/src/app/pages/main/nav/nav.component.html
- client/src/app/pages/main/nav/nav.component.scss
- client/src/app/pages/main/nav/nav.component.ts
Closes #361 
This button appears to have never worked in the first place and like it was designed for plain Bootstrap, this adds an Angular powered version and improves the layout. Should only have an affect on >960px wide screens.
Preview:
Also a minor tweak to vertical alignment:
Before:
After:
> Responsive navbar, layout tweaks

- .github/workflows/dockerimage.yml
- Dockerfile
- buildAndRunDocker.sh
- env-vars.list
- runDocker.sh
Closes #402 
This PR is a draft, as paths for persistent mounting needs to be decided.
Before this is merged, the org needs to setup GitHub packages for pushing the built images with GitHub Actions to. In addition to this, the repo needs to add a secret `GITHUB_TOKEN` for authenticating the push to GitHub packages.
> Feature: Implement docker

- buildAndRunDocker.sh
- runDocker.sh
Use `$PWD/xyz` instead of `./xyz` to fix Docker error when trying to mount volumes
Use `staging` image tag instead of `latest`
Use the full name `docker.pkg.github.com/momentum-mod/website/mmod-website:staging` in the run command instead of `mmod-website`
> Fix: A couple issues with the Docker implementation

- Dockerfile
Reduces 1.3GB+ image down to ~200MB
Should squash the commits before merging
> Fix large docker image by using a multi-stage build

- .github/workflows/dockerimage.yml
Stops multiple publish docker actions happening together, instead triggering the action when wanted.
> Use publish docker action manually

- client/src/app/pages/main/nav/nav.component.html
- client/src/app/pages/main/nav/nav.component.ts
Fixes #401 
This issue had two potential fixes:
> **1. Make the href double activate to ensure it jumps down to the element** 
> 
> 
> **Pros:**
> - Keeps the current functionality while fixing the bug exactly (href anchor will be appended to the url & the button clicks will function correctly)
> 
> **Cons:**
> - The browser back button will take two clicks to go back
> - The browser will _almost_ definitely refresh the page. This is slightly jarring for a button which just scrolls down the page
> - Could potentially cause the "you are leaving the website" popup to appear because it is technically redirecting when running the script to perform the double click
> **2. Change functionality to the on-click "(click)" action and a corresponding function call** 
> 
> **Pros:**
> - Works every …
> Fix #401 w/ javascript on (click) action

- client/src/app/@core/data/activity.service.spec.ts
- client/src/app/@core/data/activity.service.ts
- client/src/app/@theme/components/activity/activity-card/activity-card.component.html
- client/src/app/@theme/components/activity/activity-card/activity-card.component.ts
- client/src/app/@theme/components/activity/activity-list/activity-list.component.html
- client/src/app/@theme/components/activity/activity-list/activity-list.component.spec.ts
- client/src/app/@theme/components/activity/activity-list/activity-list.component.ts
For issue #200 
I used Nebular's built-in infinite list functionality. 
I wasn't sure what threshold I should have picked (0 is when scroll bar all the way down). The emitter for the activity-list will also re-emit if you keep scrolling to the bottom and back up when there are no more activities left to load but the function to handle the emit in activity-card will immediately return and not call the API if the list is exhausted. I also had to add a check that it would only load more for recent activity since I noticed activity-card was reused for followed activities. Lastly, I had to make a slight adjustment to the activity service so that I could call older activities from the API.
> Added infinite list for recent activities

- client/src/app/pages/main/gamemodes/gamemodes.component.html
- client/src/app/pages/main/gamemodes/gamemodes.component.scss
Fixes #442
Tested in Firefox and Chrome (and Edge but that's basically Chrome) at every screen width breakpoint.
I had to manually center both the image and the svg ring to their parent div. I also removed some unnecessary SVG code. Drawing the the invisible ring over the pre-existing one was not needed and moving `fill: none;` to `.base-timer__svg` kept the circle as a ring.
> Fixed gamemode circle timer alignment on main page

- client/src/app/pages/dashboard/maps/map-list/map-list.component.ts
Fixes #473
I added a check upon removal from library/favorites in `libraryUpdate()` and `libraryUpdate()` that checks for whether the user in on the last page + the last map of that page is being removed + the user isn't on page 1. Then all I needed to do was decrement the page count so it wouldn't query a page now out of index.
> Fixed pagination issue upon removal of last map in library and favorites

- server/src/controllers/auth.js
- server/src/models/user.js
Partly solves issue #258 
For the `models/user.js`, I handled the case and added an error message for when, given a list of steam ids, no players were found. I also added error messages for when the response code is not 200. 
As for the `controllers/auth.js`, I could neither find how the response object looks like for cases when `params.result !== 'OK'`, nor do I know how to generate a user ticket to test this API endpoint on Postman with. The docs for that API endpoint doesn't show the structure of the response either, so I really won't be able to properly parse `sres.data`. However, I found that if I passed in an invalid ticket value (like 0), the response body would look something like this instead:
```
{
"response": {
"error": {
"errorcode": 3,
"errordesc": "Invalid parameter"
}
}
} …
```
> Added error messages for external Steam API request errors

- client/src/app/pages/main/gamemodes/gamemodes.component.html
- client/src/app/pages/main/gamemodes/gamemodes.component.scss
Fixes #488
First I centered the text and video using `align-items-center` but it left an annoying 4ish pixel gutter at the bottom of the video seen here:
so I opted to set its parent wrapper div as another row element so I could center it again using `align-items-center`. This 4 pixel gutter might be because of the YouTube embeds since it does not occur with those so when all the videos are WebM you might be able to remove this second row element workaround.
I also removed the bottom margin for the md breakpoint and up on the wrapper div since it would offset the video when the elements are stacked side-by-side.
Lastly I removed min-height from `gamemode-data-section` since it was causing an additionally large amount of margin padding  that wasn't present on the original version. It also …
> Fixed video text vertical centering on main page

- client/src/app/pages/main/gamemodes/gamemodes.component.scss
Reported by Mellow1238 on Discord.
The boxes don't need to be dynamically sized since the text size never changes between the screen width breakpoints. I also think the original author probably meant to use pixels instead of percent since 55px seems to be about the width you'd want.
> Fixed soon™ text clipping out of its box

- client/src/app/@theme/components/search/search-field.component.html
- client/src/app/@theme/components/search/search-field.component.scss
- client/src/app/@theme/components/search/styles/search.component.modal-drop.scss
Fixes #454
The fix required setting the search results to have `overflow-y: auto` but in order for that to work you have to specify the height of the div.
Here's how it looks when you scroll down a bit:
If you want the Users and Maps headers to stay visible it would have to be broken down into two scrollable columns or the HTML layout would be need to be reworked so that the headers are in their own separate div.
I set the top margin to `10vh` instead of `10%` to simplify the height calculation for `results`. This change makes it look slightly different from before. New on the left, old on the right.
Here's how they look on an average 1920x1080 screen (non-fullscreened browser):
And here's how they would roughly look on a phone (phone resolutions differ between phones):
The `calc` …
> Added scrolling to global search results

- client/src/app/@core/data/activity.service.ts
- client/src/app/@core/data/admin.service.ts
- client/src/app/@core/data/auth.service.ts
- client/src/app/@core/data/local-user.service.ts
- client/src/app/@core/data/maps.service.ts
- client/src/app/@core/data/ranks.service.ts
- client/src/app/@core/data/report.service.ts
- client/src/app/@core/data/runs.service.ts
- client/src/app/@core/data/stats.service.ts
- client/src/app/@core/data/users.service.ts
- client/src/app/@core/guards/auth.guard.ts
- client/src/app/@core/utils/notifications.service.ts
- client/src/app/pages/dashboard/profile/profile-edit/profile-edit.component.ts
- client/src/environments/environment.prod.ts
- client/src/environments/environment.ts
Copying from discord:
I think [Cloudflare Pages](https://pages.cloudflare.com/) can host our frontend for us automatically, actually. The change would become:
Hosted on one machine, different ports are the angular and API processes, local proxy just forwards API requests to that port you're hosting it on
Any PR opened can have it hosted on a Cloudflare preview page, making it so that any frontend changes can instantly be previewed before merge, given it doesn't use API functions that don't exist yet.
Frontend hosted by cloudflare, proxies the API calls to api.momentum-mod.org, which in DNS CNAME's to the VPS that hosts the backend (and frontend currently as well, but will eventually become *JUST* backend)
Changes to only build the API and serve it on a specific port, where the VPS that …
> Move to Cloudflare Pages Frontend Hosting

- .github/workflows/dockerimage.yml
- env-vars.list
- server/config/config.js
- server/config/express.js
- server/package.json
- server/src/controllers/auth.js
- server/test/user.js
- server/yarn.lock
Closes #303 
The tradeoff with using this method is no need to do a server sided URL request to Steam, instead making that on the game client's end to get the encrypted ticket. Much better for the long run, in my opinion. We can even pass data through these tickets and parse them here, but currently it goes unused.
Controlled by env vars:
`STEAM_USE_ENCRYPTED_TICKETS` - when "true" it will enable it, otherwise falls back to old auth session ticket code
`STEAM_TICKETS_SECRET` - if above is true, this is the shared secret in Steamworks settings
> Add Steam Encrypted App Ticket parsing

- server/src/models/map-favorite.js
- server/src/models/map-library.js
- server/src/models/map.js
As Goc had mentioned and further suggested\*, this PR is for increasing the query limit for map info and the user's own library info from 20 to 100
\*suggested in the sense that he had said 100 requests and I figured I'd go with that
I'm pretty sure that there's no other places defined limiting this specific data, but I'm not 100% tho I did look
> ⚡ Increase request limits for certain map data

- client/src/app/@theme/styles/styles.scss
The scrollbar is visible at all times, even if there is nothing to scroll. Removing this property reverts it back to default behaviour.
| Before | After |
| - | - |
> Remove forced scroll overflow on entire HTML

- client/src/app/pages/dashboard/stats/global-stats/global-stats-maps/global-stats-maps.component.ts
FIX: Changed echarts legend color (so you can see it...) and changed data point name color to white so it gets rid of the weird border
> Global map stats echarts styling

- server/src/routes/api/runs.js
Closes #476 
Started with a simple one. ~~I looked into adding a button on the frontend briefly, however it would require some kind of js file download or serverside generation of an authenticated/authorised temporary link, and decided it wasn't worth the effort unless specifically required.~~ I remembered its possible to submit the jwt as a get query param.
Tested:
- `roles` column on db for user = 0
- Server returned a 403 forbidden
- `roles` column on db for user = 8
- Server returned the file from `/app/server/public/runs/<run id>`
> Implement /api/runs/:runID/download route

- .github/workflows/angularbuild.yml
- .github/workflows/test.yml
- client/src/app/pages/dashboard/stats/global-stats/global-stats-maps/global-stats-maps.component.ts
- env.TEMPLATE
- server/config/config.js
- server/src/controllers/auth.js
Checking STEAM_PREVENT_LIMITED, if it's "true" then it'll prevent limited accounts from connecting
This logic will be refactored to only "disable" limited accounts by flagging them and preventing uploading runs in the future
Updated workflow file to:
1. Only run the appropriate jobs when it detects files to run them against have changed
2. Actually run lint again (it caused some problems with the recent merge...)
3. Only run on pull requests, as direct pushes to staging did not need to be tested again
> Add "STEAM_PREVENT_LIMITED" env var + fixup tests workflow file

- server/config/config.js
- server/src/models/auth.js
- server/test/auth.js
Added configuration options for refreshToken.expTime.
Updated models/auth.genRefreshToken options to inlcude 'expiresIn' field.
Update test/auth to validate that a refresh token expires in 1 week.
Proposal to close #573
> Site refresh token expiration

- server/src/@common/filters/all-exceptions.filter.ts
- server/src/main.ts
I'm an idiot. Forget to update the filter name, we're catching everything with this now. Also, the ternary was the wrong way round, forget to revert back after changing to test stuff.
In the future if we're both working on stuff together and it's late, let's review the following day with fresh eyes.
> 🩹 - Rename exception filter

- server/src/@common/filters/all-exceptions.filter.ts
Found this when I should have got an unauthorized error but instead was returned a 500. A quick spruse up of Tom's exsisting work and we have something that fits all HTTP errors a bit better while retaining the functionality of hiding the details of DB errors from clients and having easily lookup able logs with the error codes.
> fix: Exception filter changed all errors to 500

- server/config/config.template.ts
- server/config/config.ts
- server/src/@common/sentry/sentry-exception/sentry-exception.service.ts
- server/src/@common/sentry/sentry.module.ts
This will stop any accidental errors from spamming up sentry, it will also show pretty clearly in logs when there is a dev error vs a production error
> Sentry should only send if in production

- server/src/main.ts
- server/tests/e2e-environment.ts
This allows our bootstrapping of the app to be as similar as possible
between production and jest testing. 
It should lower risk of errors showing in on version of a build (eg in test but not production) by properly enabling settings in predefined functions.
> Safer app bootstrapping

- server/src/modules/activities/activities.controller.ts
- server/src/modules/admin/admin.controller.ts
- server/src/modules/admin/admin.service.ts
- server/src/modules/auth/auth.controller.ts
- server/src/modules/auth/auth.service.ts
- server/src/modules/auth/guard/roles.guard.ts
- server/src/modules/auth/steam-auth.service.ts
- server/src/modules/auth/strategy/jwt.strategy.ts
- server/src/modules/auth/strategy/steam-web.strategy.ts
- server/src/modules/filestore/file-store-cloud.service.ts
- server/src/modules/filestore/file-store-utils.service.ts
- server/src/modules/maps/maps.controller.ts
- server/src/modules/maps/maps.service.ts
- server/src/modules/repo/maps-repo.service.ts
- server/src/modules/repo/users-repo.service.ts
- server/src/modules/reports/reports.controller.ts
- server/src/modules/runs/runs.controller.ts
- server/src/modules/user/user.controller.ts
- server/src/modules/users/users.controller.ts
- server/src/modules/users/users.service.ts
Another sweeping refactor, I'm sorry. I just strongly feel we should be following a consistent naming style, meaning lowerCamelCase for method names. I plan on enforcing https://ts.dev/style/#naming-style from now on.
Also, using `public` on the front of methods everywhere is just silly (and we weren't even applying it consistently). It has no programmatic purpose, seems to just be there for the sake of looking like C++/C#/Java. More than anything I worry it'll confuse contributors into thinking it has actual practical purpose.
> chore: Refactor method names and access

- server/package.json
This screws up tests and is generally unnecessary, better to just have the seed command do this.
> Don't seed after Prisma Migrate

- server/src/@common/dto/map/map-credit.dto.ts
- server/src/@common/dto/map/map-info.dto.ts
- server/src/@common/dto/query/map-queries.dto.ts
- server/src/modules/admin/admin.service.ts
- server/src/modules/maps/maps.controller.ts
- server/src/modules/maps/maps.service.ts
- server/src/modules/repo/maps-repo.service.ts
- server/src/modules/repo/users-repo.service.ts
- server/tests/maps.e2e-spec.ts
We got the following endpoints:
- maps/:mapID/credits GET, POST  
- maps/credits/:mapCredID GET, PATCH, DEL  
- maps/:mapID/info GET, PATCH  
- maps/:mapID/zones GET  
I decided not to bother messing around moving any service logic, imo it's probably best to do all of that in one go anyways
> More maps endpoints

- docker-compose.override.yml
Haven't tested this, but indention was clearly broken, might as well fix
> fix: Indentation of docker-compose

- server/src/modules/users/users.service.ts
This was already broken but it didn't really matter, until I made it so aliases are non-nullable. Fixes that error for now, I'll rework this method in the near future.
> fix: Temp fix for openid user creation

- server/src/modules/filestore/file-store-cloud.service.ts
- server/src/modules/maps/maps.controller.ts
- server/src/modules/maps/maps.service.ts
- server/tests/e2e/maps.e2e-spec.ts
There are some things I'd like to get input about, which I was very unsure of while writing the changes
1.  I didn't know if I should log a failed download, I decided to do so and include the error message, since an invalid key or bucket can  throw different errors
1.  I included the response type from express to pass the object to the service, I think I could have gotten away with the `any` type but did so for clarity
1.  If `maps.service.ts` LN: 330 fails, the download won't start. I thought about catching and ignoring the potential error there so that a failed downloadCounter increment doesn't stop a download, alternatively I could have created a service function to increment the counter after writing to the response
> GET maps/:mapID/download

- server/src/main.ts
- server/src/modules/activities/activities.controller.ts
- server/src/modules/admin/admin.controller.ts
- server/src/modules/auth/auth.controller.ts
- server/src/modules/maps/maps.controller.ts
- server/src/modules/reports/reports.controller.ts
- server/src/modules/runs/runs.controller.ts
- server/src/modules/session/session.controller.ts
- server/src/modules/stats/stats.controller.ts
- server/src/modules/user/user.controller.ts
- server/src/modules/users/users.controller.ts
`auth.*` doesn't get parsed as a regular expression when trying to exclude paths from `setGlobalPrefix`, and instead uses wildcards provided by path-to-regexp. `auth(.*)` is parsed as a regular expression so it properly excludes auth. Hooray
> Fix API versioning

- .editorconfig
This PR provides a configuration file for [EditorConfig](https://editorconfig.org/).
tl;dr it's a standard file to allow most IDE/text editors (through an extension) to set-up style-related settings like size of indents, and more. It's opt-in (you need the extension for your IDE to use it) and it would allow everyone to have proper tabs (my VSCode uses 4 by default and its auto-indent doesn't always work).
Note to reviewers:
- I've set-up a general indent size of 2 since most `.scss`, `.ts` and `.html` files I've delved in were using such size, but if there are other sizes for different file types in can be provided
> Enable editorconfig

- commitlint.config.js
Dependabot PRs fail linting checks currently, this should fix.
> chore(meta): add scope used by Dependabot to commitlint config

- .github/workflows/test.yml
For some jobs the E2E affected checks pass automatically because the command is run with wrong args - we need to explicitly pass in the base and head SHAs.
Also, noticed we were doing a pointless `git fetch` explicitly - `actions/checkout` can handle it for us. The `--no-prune` and `--no-tags` args don't seem that important, other Nx CI setups I've found mostly seem to just use `actions/checkout` with this config.
> Fix: Broken Nx affected in E2E jobs

- .github/workflows/test.yml
This workflow can sometimes fail if the Prisma schema changes, but nothing has changed in the package.json, since the Prisma client generation is only run as the `postinstall` step of `npm install`, which won't run if the runner successfully hits the node_modules cache.
~~Note: don't merge immediately, want to check CI runs correctly.~~ Okay all good
> ci: always run prisma generate

- .github/workflows/test.yml
Sorry, should've tested the first PR more. I've tested this one on Afranche's PR branch. Turns out this was way harder than I anticipated!
You can't update a cache once it's made, so sharing the Prisma between jobs is quite annoying. My solution is to use two caches: one for the original node_modules, another for node_modules + the Prisma client.
> ci: properly cache results of prisma generate

- apps/frontend/src/app/pages/dashboard/dashboard.component.html
- apps/frontend/src/app/pages/dashboard/dashboard.component.scss
- libs/frontend/theme/src/styles/font-size.scss
- libs/frontend/theme/src/styles/styles.scss
- libs/frontend/theme/src/styles/theme.scss
This is by no means a complete restyle, frankly it doesn't look great (still better than current stuff). I think it's worth getting this work in now though - it's probably going to be a couple of months until I can focus on styling and this gives other contributors something closer to what our dashboard will look like in the future.
Main issue is font-size scaling, which effectively rescales *everything* on the site, and I've much rather contributors design stuff using regular 16pt scaling, even if some parts of the existing UI might look a bit worse with this change. Better they work with the correct scaling now and get stuff looking good, than they do something for the 14pt scaling, and we have to go in and tweak it again once we do the full restyle.
> Initial frontend styling

- apps/backend-e2e/src/maps.e2e-spec.ts
- apps/backend/src/app/modules/maps/map-review.service.ts
- apps/backend/src/app/modules/maps/maps.controller.ts
- libs/backend/dto/src/queries/map-queries.dto.ts
- libs/constants/src/types/queries/map-queries.model.ts
E2E tests included.
Closes #805
> Added GET maps/{mapID}/reviews/{reviewID} endpoint 

- apps/frontend/src/app/components/header/header.component.ts
- apps/frontend/src/app/pages/dashboard/profile/profile-edit/profile-edit.component.ts
- apps/frontend/src/app/pages/dashboard/profile/profile-redirect.component.ts
- apps/frontend/src/app/pages/dashboard/profile/profile-routing.module.ts
- apps/frontend/src/app/pages/dashboard/profile/profile.module.ts
Someone earlier asked how they can link find a URL to their profile, given that if they navigate to their profile page on the frontend, they just go to /dashboard/profile, and don't know their userID.
The simplest solution to me is to just always use the relativized URL containing the user's id. Incidentally this seems to be how most sites handle profile pages.
> refactor(front): remove /profile page, always use /profile/{userID}

- apps/backend-e2e/src/admin.e2e-spec.ts
- apps/backend-e2e/src/auth.e2e-spec.ts
- apps/backend-e2e/src/user.e2e-spec.ts
- apps/backend/src/app/modules/users/users.service.ts
- apps/frontend/src/app/components/delete-user-dialog/delete-user-dialog.component.html
- libs/db/src/prisma/schema.prisma
Closes https://github.com/momentum-mod/website/issues/852
> Prevent deleted users from recreating account

- docker-compose.override.yml
Usually Prisma Studio is fine for checking DB contents, but I've been finding [pgadmin](https://www.pgadmin.org/) useful for benchmarking and messing with raw queries. This lets you include it in the typical Docker dev setup with `docker compose --profile pgadmin up`
> Add optional pgadmin container to dev docker compose config

- apps/backend-e2e/src/prisma.e2e-spec.ts
- apps/backend/src/app/modules/xp-systems/xp-system.service.spec.ts
- apps/backend/src/app/modules/xp-systems/xp-systems.service.ts
- libs/db/src/prisma/schema.prisma
> fix(back,db): sets the initial level for users to 0

- apps/backend-e2e/src/prisma.e2e-spec.ts
- libs/db/src/prisma/schema.prisma
- libs/xp-systems/src/constants.ts
- libs/xp-systems/src/xp-system.class.spec.ts
- libs/xp-systems/src/xp-systems.class.ts
Split these changes out from https://github.com/momentum-mod/website/pull/876 so we can review separately. Sorry that it's still on top of all those commits, some file renaming/moving requires it, this branch is really just the last two commits!
So, I completely misunderstood how new user cosmetic XP/level assignment worked, getting the wrong impression that new users were supposed to start at 20,000 XP. This was completely my own fault, I ported some of the initial XP systems code from the old backend wrong, and assumed the weird behaviour was a result of the original design, not my own crappy porting. Apologies for that! This reverts to the original constants, and **starts new users with the correct starting values of level 1, 0 XP**. I don't test that directly, but hopefully …
> Revert XP constant changes

- libs/db/src/scripts/seed.ts
One of the recent Prisma updates seems to have changed how values passed to `undefined` behave, which as far as I can tell, only affects this script. We don't run this in CI at all, so it got through tests on Gordi's recent PR.
Gordi, this will probably fix any issue with work you're doing, so feel free to rebase this in as soon as you approve.
> Fix seed script on latest Prisma

- apps/backend-e2e/src/user.e2e-spec.ts
- apps/backend/src/app/modules/users/users.service.ts
- apps/frontend/src/app/pages/profile/profile.component.ts
This change prevents a user from following themself by both removing the "Follow" button from the profile view for the logged in user and by checking that target and logged in user are not the same in the follow API.
Closes #892
I simply removed the follow button component when viewing the logged in user's profile as this is not a bug in production so there should not be a risk of real users having following themself. If desired I can rework this to remove only the "Follow" button leave the "Unfollow" button.
> Disallow self follow

- apps/backend-e2e/src/maps-2.e2e-spec.ts
- apps/backend/src/app/dto/queries/map-queries.dto.ts
- apps/backend/src/app/modules/maps/maps.controller.ts
- apps/backend/src/app/modules/runs/leaderboard-runs.service.ts
- libs/constants/src/types/queries/map-queries.model.ts
- libs/db/src/scripts/seed.ts
Doesn't make sense for these hashes to be null, and this allows Panzer to use these in game code.
> Leaderboard fixes for Panzer

- apps/backend-e2e/src/maps.e2e-spec.ts
- apps/backend/src/app/dto/queries/map-queries.dto.ts
- apps/backend/src/app/modules/maps/maps.service.spec.ts
- apps/backend/src/app/modules/maps/maps.service.ts
- libs/constants/src/types/queries/map-queries.model.ts
- libs/db/src/scripts/seed.ts
Small PR for once! 
- All users can now see maps that are in `FINAL_APPROVAL`
- Creditors and testers can still see maps in `CONTENT_APPROVAL`
- /maps/submission  to request maps with specific filters
We'll be using this in game code to request in `PRIVATE_TESTING` and `CONTENT_APPROVAL`, since `PUBLIC_TESTING` and `FINAL_APPROVAL` are stored in the static map cache.
> Map submission status visibility changes

- apps/backend-e2e/src/support/environment.ts
- apps/backend/src/app/app.module.ts
- apps/backend/src/app/config/config.interface.ts
- apps/backend/src/app/config/config.ts
- apps/backend/src/app/config/config.validation.ts
This is very helpful in tests, replacing the old "TEST_LOG_DEBUG" var. By default, E2E tests don't spew INFO logs anymore.
> Add LOG_LEVEL env var

- apps/backend-e2e/src/support/global-setup.ts
Osplo me and MinimumDonut have all been having issues with WebStorm loading environment variables lately. To be honest I'm not sure why it started happening. This just uses `dotenv` (which we have already) to load the file during E2E test setup.
> fix(back-e2e): help WebStorm load .env files

- apps/frontend/src/app/components/map-forms/map-leaderboard-selection/map-leaderboards-selection.component.html
This PR addresses and fixes issue #948 by adding the type attribute to the buttons within the leaderboard component.   
In Angular, if the button doesn't have a defined attribute type, then Angular may be trying to issue the keyup event and trigger the on click method for the button. 
Closes #948
> Prevent buttons from creating additional fields

- apps/backend-e2e/src/auth.e2e-spec.ts
- apps/backend-e2e/src/user.e2e-spec.ts
- apps/backend/src/app/dto/user/user.dto.ts
- apps/backend/src/app/modules/users/users.service.spec.ts
- apps/backend/src/app/modules/users/users.service.ts
- apps/frontend/src/app/pages/profile/profile-edit/profile-edit.component.html
- apps/frontend/src/app/pages/profile/profile-edit/profile-edit.component.ts
- libs/constants/src/index.ts
- libs/constants/src/regexp/non-whitespace.regexp.ts
Date:      Fri May 31 10:58:39 2024 -0500
Implements fix for bug #921
Implements fix for bug #921 which resets the users alias on logou and back in. This fix
- Implements a new regex to disallow purely whitespace based aliases
- E2e testing on the new aliases
- Logic to test if the user name is valid, or is the default value
Closes #921
> Add logic to prevent changing user alias on logout/login

- apps/backend-e2e/src/maps.e2e-spec.ts
- apps/backend-e2e/src/multi-stage.e2e-spec.ts
- apps/backend/src/app/config/config.interface.ts
- apps/backend/src/app/config/config.ts
- apps/backend/src/app/dto/index.ts
- apps/backend/src/app/dto/map/map-pre-signed-url.dto.ts
- apps/backend/src/app/dto/map/map.dto.ts
- apps/backend/src/app/modules/filestore/file-store-s3.service.ts
- apps/backend/src/app/modules/filestore/file-store.service.ts
- apps/backend/src/app/modules/maps/maps.controller.ts
- apps/backend/src/app/modules/maps/maps.service.ts
- apps/frontend/src/app/pages/maps/map-edit/map-edit.component.ts
- apps/frontend/src/app/pages/maps/submission-form/map-submission-form.component.ts
- apps/frontend/src/app/services/data/maps.service.ts
- docker-compose.override.yml
- libs/constants/src/consts/limits.const.ts
- libs/constants/src/types/models/index.ts
- libs/constants/src/types/models/map/map-pre-signed-url.model.ts
- libs/constants/src/types/models/map/map-submission-version.model.ts
- libs/constants/src/types/models/map/map.model.ts
- libs/test-utils/src/utils/s3.util.ts
- package-lock.json
- package.json
Closes #705
Closes #318 
When uploading BSP for map submission s3 pre-signed urls will be used now.
> Pre-signed urls for map submission

- apps/backend-e2e/src/auth.e2e-spec.ts
- apps/backend-e2e/src/support/environment.ts
- apps/backend-e2e/src/users.e2e-spec.ts
- apps/backend/src/app/filters/exception-handler.filter.ts
- apps/backend/src/app/modules/auth/auth.controller.ts
- apps/backend/src/main.ts
- apps/frontend/src/app/env/environment.ts
- libs/test-utils/src/utils/request.util.ts
The new production deploy uses api.momentum-mod.org / staging-api.momentum-mod.org, so /api/ is redundant. In dev I don't think the prefix is particularly helpful either.
> refactor(shared): remove /api prefix on backend URLs

- .github/workflows/backend_docker_image.yml
- .github/workflows/frontend_cf_pages.yml
- .github/workflows/test.yml
Bumps us to latest Node version, squashes warning in output.
Also moved us to wrangler directly to publish to cloudflare, seems like the pages action hasn't been updated in a while and will continue to give the Node 20 warning, whilst the wrangler action works fine and is kept up to date.
> Update CI to use Node 20 based jobs

- apps/frontend/src/app/pages/profile/profile-edit/profile-edit.component.html
As suggested by BJack0 on discord, enables search bar for country selector on profile edit page
> Enable filter bar for country selector in profile edit

- .github/dependabot.yml
Was trying to bump @schematics/angular to 18.0.7 whilst other Angular stuff (which we do manually) is on 18.0.6.
> ci(meta): ignore all angular-related packages in auto update

- prod/Dockerfile
Makes all files in /app folder of docker container be owned by backend user.
Should help with migration errors
> fix(build): Make backend user in docker own node_modules

- .github/dependabot.yml
- apps/backend/src/app/config/config.ts
- libs/test-utils/src/utils/db.util.ts
- libs/test-utils/src/utils/request.util.ts
Dependabot recently upgraded Prettier, which makes our formatting checks in CI fail. We're not going to be in desperate need to upgrade Prettier, fine to do manually.
> Stop dependabot bumping Prettier

- apps/backend/src/app/modules/maps/maps.service.ts
This was a case of me keeping a Prisma transaction open for the lifetime of several S3 requests. I've pulled out the S3 logic to run in a separate task that won't block the DB work.
Haven't written tests for this since I can't think of a reliable way to E2E test this and we'll test it out on staging tonight.
Closes #998
> Fix Prisma transaction timeout during map submission

- .eslintrc.js
- apps/backend-e2e/src/admin.e2e-spec.ts
- apps/backend-e2e/src/maps-2.e2e-spec.ts
- apps/backend-e2e/src/maps.e2e-spec.ts
- apps/backend-e2e/src/session.e2e-spec.ts
- apps/backend/src/app/app.module.ts
- apps/backend/src/app/config/config.ts
- apps/backend/src/app/dto/map/map-version.dto.ts
- apps/backend/src/app/modules/map-review/map-review.service.ts
- apps/backend/src/app/modules/maps/maps.controller.ts
- apps/backend/src/app/modules/maps/maps.service.ts
- apps/backend/src/app/modules/session/run/run-processor.class.spec.ts
- apps/backend/src/app/modules/session/run/run-processor.class.ts
- docker-compose.test.yml
- libs/db/project.json
- libs/db/src/migrations/20240927170504_map_zone_strings/migration.sql
- libs/db/src/schema.prisma
- libs/formats/zone/src/zones.stub.ts
- libs/test-utils/src/utils/db.util.ts
- libs/test-utils/src/utils/request.util.ts
- scripts/src/seed.script.ts
Refactors backend/DB so that zones are stored as plain `text` rather than `jsonb`.
With incoming map cache changes, we perform a hash check on map load to check zone files match the hash on the `zoneHash` field of the `MapVersion` table. Currently, zones are stored in Postgres as `jsonb`, a Postgres-specific binary serialization of JSON. It doesn't store whitespace, so makes storing zone hashes unreliable - it's *probably* possible to get the hash check to be consistent but I was struggling to get it working and felt very messy.
The main purpose of `jsonb` is to allow queries over that JSON data, which for zones we never need to do - we're really just using using the field for storage. The only thing we gain from using `jsonb` is that Prisma queries automatically parse the JSON into JSOs …
> Use plain strings for map zones

- commitlint.config.js
- docker-compose.test.yml
- docker-compose.yml
Latest version of MinIO fails in test CI for some reason. Just pinning to a working version, we only use it for dev/test CI anyway.
> Fix MinIO in CI

- apps/backend/src/app/dto/map/map-zones.dto.ts
Fixes e2e backend tests after model changes for map zones
> fix(back): Mark allow bhop regions as optional

- apps/frontend/src/app/components/map-forms/map-leaderboard-selection/map-leaderboard-selection.component.ts
- apps/frontend/src/app/components/map-forms/map-leaderboard-selection/map-leaderboards-selection.component.html
Closes #1051
Fix map submission and editing ranked status
> fix(front): fix map submission and editing ranked status

- apps/frontend/src/app/components/level-indicator/level-indicator.component.html
- apps/frontend/src/app/components/level-indicator/level-indicator.component.ts
- apps/frontend/src/app/components/player-card/player-card.component.ts
- apps/frontend/src/app/pages/profile/profile.component.html
- apps/frontend/src/app/pages/profile/profile.component.ts
- libs/random/src/index.ts
- libs/util-fn/src/array-from.ts
- libs/xp-systems/src/constants.ts
- libs/xp-systems/src/xp-system.class.spec.ts
- libs/xp-systems/src/xp-systems.class.ts
- scripts/src/seed.script.ts
Closes #1045
Changes the code precalculating XP values in xp-systems to match [C++](https://github.com/momentum-mod/game/blob/develop/mp/src/game/shared/momentum/util/mom_system_xp.cpp). We don't unit test the C++ code, but I've manually checked all the expected values in our unit tests with the C++ version using a debugger.
After this change, the frontend components have the correct values (0 / 21000 XP for new user at level 1).
I also improved the docs for these functions (which were partially the cause of the confusion here) and cleaned up the xp-systems class a bit.
> Fix cosmetic xp calculations

- apps/backend-e2e/src/maps.e2e-spec.ts
- apps/backend-e2e/src/users.e2e-spec.ts
- apps/backend/src/app/config/config.interface.ts
- apps/backend/src/app/config/config.ts
- apps/backend/src/app/dto/user/user.dto.ts
- apps/backend/src/app/modules/maps/map-webhooks.service.ts
- apps/backend/src/app/modules/maps/maps.module.ts
- apps/backend/src/app/modules/maps/maps.service.ts
- libs/constants/src/consts/steam-avatar.const.ts
- libs/constants/src/consts/steam-default-avatar.const.ts
- libs/constants/src/index.ts
- scripts/src/seed.script.ts
Closes #607
Adds triggering discord webhooks for when map goes to public testing or was approved.
Tom, if you want me to move webhook service to separate module please comment here, I'm just not that sure about it.
> Discord webhook notifications

- apps/backend-e2e/src/admin.e2e-spec.ts
- apps/backend-e2e/src/maps.e2e-spec.ts
- apps/backend/src/app/dto/map/map-version.dto.ts
- apps/backend/src/app/modules/maps/leaderboard-handler.util.spec.ts
- apps/backend/src/app/modules/maps/leaderboard-handler.util.ts
- apps/backend/src/app/modules/maps/map-list.service.spec.ts
- apps/backend/src/app/modules/maps/map-list.service.ts
- apps/backend/src/app/modules/maps/maps.service.ts
- apps/frontend/src/app/components/map-forms/map-status-form/map-status-form.component.ts
- libs/random/src/index.ts
- libs/test-utils/src/utils/s3.util.ts
- scripts/src/seed.script.ts
Adds a simple header block to static map lists storing
- ident
- length of uncompressed data
- number of maps
Makes C++ allocs faster and simpler.
> Static map list headers

- commitlint.config.js
> fix(ci): Force scopes in commits to not be empty

- apps/frontend/src/app/util/grouped-map-leaderboards.util.ts
Closes #1084 
Makes sorting for leaderboard grouping definitive. Looks like chrome and firefox array sort implementations are a bit different, where first and second argument for sort function are switched. The issue is not just with firefox and based on how leaderboards are sorted initially when created (which is also affected by what browser map is submitted from)
> fix(front): Fixed sorting when grouping leaderboards

- apps/frontend/src/app/directives/textarea-allow-enter.directive.ts
- apps/frontend/src/app/shared.module.ts
This is because forms can eat the input, really gross. Made a global directive so this is never an issue in the future.
> fix(front): enter key not working in <textarea> elements

- apps/backend-e2e/src/maps.e2e-spec.ts
- apps/backend/src/app/modules/admin/admin.controller.ts
- apps/backend/src/app/modules/map-review/map-review.controller.ts
- apps/backend/src/app/modules/maps/maps.controller.ts
- apps/backend/src/app/modules/user/user.controller.ts
- apps/backend/src/app/modules/users/users.controller.ts
- apps/backend/src/app/pipes/index.ts
- apps/backend/src/app/pipes/parse-int-32-safe.pipe.ts
Created `ParseInt32SafePipe` and changed every usage of `ParseIntSafePipe` for database IDs (where IDs are actually INT4) to new pipe
> Safer number parsing for database IDs

- apps/backend/src/app/modules/maps/map-webhooks.service.ts
> fix(back): use map name rather than id in url in map announce webhook

- apps/frontend/src/app/components/map-forms/map-leaderboard-selection/map-leaderboard-selection.component.ts
- apps/frontend/src/app/components/map-forms/map-leaderboard-selection/map-leaderboards-selection.component.html
When adding second main leaderboard suggestion for different gamemode, the track num of this suggestion can become different from one if there are any bonuses present, because of https://github.com/momentum-mod/website/blob/1da3c4d6fb3e6933e9500862e4b37d3a2dc1d80f/apps/frontend/src/app/components/map-forms/map-leaderboard-selection/map-leaderboard-selection.component.ts#L90
This PR fixes this by making sure that every suggestion with main track type will have track num 1
Before 
After
> fix(front): Change track num to 1 when main track type is selected

- apps/backend-e2e/src/maps.e2e-spec.ts
- apps/backend/src/app/modules/maps/maps.service.ts
- apps/frontend/src/app/pages/maps/map-edit/map-edit.component.html
- apps/frontend/src/app/pages/maps/map-edit/map-edit.component.ts
- apps/frontend/src/app/validators/index.ts
- apps/frontend/src/app/validators/map-edit.validator.ts
Closes #1080 
Changed map version submission and added a validator in frontend;
Changed service to be prepared to not have a bsp in temp in backend;
> fix(shared): allow updating only one file from map version

- apps/backend/src/app/dto/map/map.dto.ts
- apps/backend/src/app/modules/maps/maps.service.ts
- apps/frontend/src/app/components/map-forms/map-details-form/map-details-form.component.html
- apps/frontend/src/app/components/map-forms/map-details-form/map-details-form.component.ts
- apps/frontend/src/app/pages/maps/map-edit/map-edit.component.ts
- apps/frontend/src/app/pages/maps/submission-form/map-submission-form.component.ts
- libs/constants/src/types/queries/map-queries.model.ts
Closes #1097
Added field to map submission form to add changelog when submission type is Port
> chore(shared): added changelog field to map submission when type is port

- apps/frontend/src/app/pages/maps/map-info/map-leaderboard/map-leaderboard.component.html
- apps/frontend/src/app/pages/maps/map-info/map-leaderboard/map-leaderboard.component.ts
Forgot to convert this to 1-indexing. Fix for main track leaderboards not showing, and stages + bonuses being the wrong trackNum by 1.
Fixed this on the run-submission branch and forgot to separate out to a new PR, sorry!
Closes #
> fix(front): map-leaderboards component using wrong trackNum offset

- apps/backend/eslint.config.cjs
Tiny linter thing I noticed affecting `main.ts` immediately after merging the big deps branch... :)
> fix(lint): backend-specific linter rules not affecting files

- .github/dependabot.yml
- package-lock.json
Stop Dependabot from doing non-security related PRs -- they're spammy and unhelpful.
> Update Dependabot to only handle security updates

- .github/workflows/test.yml
- libs/constants/.nxignore
- libs/constants/project.json
- libs/constants/tsconfig.json
- libs/constants/tsconfig.prisma-types.json
This reverts commit 20fd32c6b1e2579073f48255aa8eb25b30988ba1.
Moving Twitch types to constants now requires building constants module, which also includes prisma types, and there is no need for discord bot to have prisma as a dependecy
> Exclude prisma dependecy from constants module and check type correspondence in ci

- apps/backend-e2e/src/activities.e2e-spec.ts
- apps/backend-e2e/src/admin.e2e-spec.ts
- apps/backend-e2e/src/auth.e2e-spec.ts
- apps/backend-e2e/src/map-review.e2e-spec.ts
- apps/backend-e2e/src/maps-2.e2e-spec.ts
- apps/backend-e2e/src/maps.e2e-spec.ts
- apps/backend-e2e/src/multi-stage.e2e-spec.ts
- apps/backend-e2e/src/reports.e2e-spec.ts
- apps/backend-e2e/src/runs.e2e-spec.ts
- apps/backend-e2e/src/session.e2e-spec.ts
- apps/backend-e2e/src/support/environment.ts
- apps/backend-e2e/src/user.e2e-spec.ts
- apps/backend-e2e/src/users.e2e-spec.ts
- apps/backend/src/app/modules/database/db.service.ts
Prisma started complaing about having too many clients open when trying to run all E2E tests local after recent dependency upgrades. Turns out I'm a complete moron and was never disconnecting the Prisma clients used by each test.
> fix(back-e2e): disconnect Prisma clients in teardownE2ETestEnvironment

- apps/backend-e2e/src/maps.e2e-spec.ts
- apps/backend/src/app/dto/map/map-version.dto.ts
- apps/backend/src/app/modules/maps/maps.service.ts
- apps/frontend/src/app/pages/maps/map-edit/map-edit.component.ts
- libs/constants/src/types/queries/map-queries.model.ts
Fixes an issue when there is an unused temporary BSP submitted by the user, which can be unintentionally used when submitting new map version
> feat(shared): Add a flag for including a BSP in a map version

- apps/backend/src/app/dto/map/map-version.dto.ts
This fixes map list not generating download urls properly
> fix(back): exclude bsp and vmf download ids only from plain objects

- libs/formats/zone/src/zone-validator.ts
Just keeping these low while still being quite generous for any reasonable map. I don't think we would ever accept a map with 200 bonuses, for example, so we should set expectations up front and we can always increase these limits later.
> Decrease max allowed checkpoints, bonus tracks, and regions

- libs/constants/src/enums/map-tag.enum.ts
- libs/constants/src/maps/map-tags.map.ts
Discussed in today's meeting, often maps don't have any identifying mechanics so we're calling them "Mixed". But vague, but seems helpful for filtration so worth having.
> feat(shared): add "Mixed" map tag

- apps/backend-e2e/src/maps-2.e2e-spec.ts
- apps/backend/src/app/modules/maps/map-test-invite.service.ts
Temporarily allows us to use private testing before adding ui to accept tests in frontend.
> Make private test invites accepted on creation

- apps/backend-e2e/src/auth.e2e-spec.ts
- apps/backend/src/app/dto/user/user.dto.ts
- apps/backend/src/app/modules/auth/steam/steam-game.guard.ts
- apps/backend/src/app/modules/auth/steam/steam-openid.service.spec.ts
- apps/backend/src/app/modules/auth/steam/steam-openid.service.ts
- apps/backend/src/app/modules/auth/steam/steam-web.guard.ts
- apps/backend/src/app/modules/steam/steam.service.ts
- apps/backend/src/app/modules/users/users.service.spec.ts
- apps/backend/src/app/modules/users/users.service.ts
- apps/frontend/src/app/pages/maps/map-info/map-info.component.html
- apps/frontend/src/app/pages/profile/profile-edit/profile-edit.component.html
- apps/frontend/src/app/pages/profile/profile-edit/profile-edit.component.ts
- apps/frontend/src/app/services/data/admin.service.ts
- apps/frontend/src/app/services/data/local-user.service.ts
- libs/constants/src/types/queries/user-queries.model.ts
Before we were calling steam for user data every time user tries to authenticate to update out saved data, but it doesn't make much sense. So now we would call steam only for user account creation
> Make auth call Steam's GetPlayerSummaries much less

- apps/backend/src/app/config/config.interface.ts
- apps/backend/src/app/config/config.ts
- apps/backend/src/app/modules/steam/steam.service.ts
Adding this in another attempt to make Steam API calls not throw 429 errors.
> Use Steam partner api url

- apps/backend-e2e/src/multi-stage.e2e-spec.ts
- apps/backend/src/app/modules/maps/maps.service.ts
- apps/frontend/src/app/components/map-list/map-list-item.component.html
- apps/frontend/src/app/directives/font-size-lerp.directive.ts
- apps/frontend/src/app/pages/maps/map-info/map-info.component.html
- apps/frontend/src/app/pages/profile/profile.component.html
Fixes an issue where a map file would be deleted if the last version didn't include the file, but was referencing the older one.
This PR also includes a commit with better text scaling algorithm. I just had it lying around for a while.
> Don't remove last version when approving a map

- apps/discord-bot-internal/src/services/streams.ts
- apps/discord-bot-internal/src/twitch-api.ts
Closes #1127
Made so that bot fetches ended streams to see if they actually ended since twitch api sometimes just doesn't provide some active streams when fetching them by category
> Fix discord double pings

- apps/backend-e2e/src/map-review.e2e-spec.ts
- apps/backend/src/app/modules/map-review/map-review-comment.service.ts
- apps/frontend/src/app/components/map-review/map-review.component.ts
Added an adecuate message when the review has been deleted, also made it so the review list updates in case the error is triggered.
> fix(front): update review list in the case we comment on a deleted review

- apps/backend/src/app/modules/session/run/run-processor.class.spec.ts
- apps/backend/src/app/modules/session/run/run-processor.class.ts
> fix(back): use main track segements for defrag bonuses

- apps/frontend/src/app/components/map-forms/map-credits-selection/map-credits-selection.component.html
- apps/frontend/src/app/components/map-forms/map-credits-selection/map-credits-selection.component.ts
- apps/frontend/src/app/components/map-forms/map-image-selection/map-image-selection.component.html
- apps/frontend/src/app/components/map-forms/map-image-selection/map-image-selection.component.ts
Thumbnail asterisk in Images section was previously not hoverable.
Also added new hoverable "required" tooltip to Author in Credits section, since it's a required field.
> Add / fix map submission required tooltips

- apps/frontend/src/app/pages/maps/map-edit/map-edit.component.html
- apps/frontend/src/app/pages/maps/submission-form/map-submission-form.component.html
closes #1124 
I just disabled the percentage from showing,
both when submitting map, and when updating existing submission with new bsp, since bug is for both.
Not sure if this was what I was actually supposed to do, but I think it looks good without a percentage showing somewhere (else).
> fix(front): progress percentage on BSP upload

- apps/frontend/src/app/theme/primeng-preset.ts
Closes #1169 
Disables the value changed animation which was previously triggered when switching between two profiles with different xp values. 
No visual changes to xp bar. See #1169 for original behavior.
NG doesn't support disabling this natively - opted for a css override. Imo it's small enough to be inline, but if it needs to be moved let me know.
> fix(front): remove animation on profile xp bar

- .github/pull_request_template.md
- apps/backend-e2e/src/admin.e2e-spec.ts
- apps/backend-e2e/src/auth.e2e-spec.ts
- apps/backend-e2e/src/user.e2e-spec.ts
- apps/backend/src/app/modules/users/users.service.spec.ts
- apps/backend/src/app/modules/users/users.service.ts
- create-migration.sh
- libs/db/src/migrations/20250617213140_hash_deleted_users/migration.sql
- libs/db/src/schema.prisma
For better GDPR compliance we shouldn't know who's deleted their accounts. We *do* need to be able to stop them from new sign-ups, so they can't flood leaderboards, so we can just hash the SteamID, use that as primary key in `DeletedUser` table, and check for that for new sign-ups.
Could use an even stronger hash if needed but SHA-256 is still secure. Not salting as no two SteamIDs could ever be in this table.
> Securely hash SteamID of deleted users

- apps/backend-e2e/src/admin.e2e-spec.ts
- apps/backend-e2e/src/maps.e2e-spec.ts
- apps/backend/src/app/modules/admin/admin.controller.ts
- apps/backend/src/app/modules/maps/maps.controller.ts
- apps/backend/src/app/modules/maps/maps.service.ts
- apps/frontend/src/app/pages/maps/map-edit/map-edit.component.html
- apps/frontend/src/app/pages/maps/map-edit/map-edit.component.ts
- apps/frontend/src/app/pages/maps/map-info/map-info.component.html
- apps/frontend/src/app/services/data/maps.service.ts
Closes #1132
Adds a button for submitter to delete their map before it was approved.
> Allow maps to be deleted before approval

- apps/frontend/src/app/pages/maps/browsers/admin-maps-browser.component.ts
- apps/frontend/src/app/pages/maps/browsers/map-browser.component.ts
- apps/frontend/src/app/pages/maps/browsers/map-submission-browser.component.ts
- apps/frontend/src/app/pages/maps/browsers/user-maps-browser.component.ts
When interacting with map browser filters, the other browsers stop working.
This is because after minification, all constructors for each map browser component is called that same thing.
So persistence key for filters will be the same, for all filters/browsers.
Changed to be hard-coded strings instead of using constructor name.
> fix(front): map filter persistence key

- apps/backend/src/app/modules/maps/maps.controller.ts
Fixes forbidden exception when trying to update map credits as a user without mapper role
> fix(back): remove role guard from credits update endpoint

- apps/frontend/src/app/components/map-forms/map-credits-selection/map-credits-selection.component.html
- apps/frontend/src/app/components/map-forms/map-credits-selection/map-credits-selection.component.ts
Closes #1231
I could have changed to use $index instead of id and alias, which would have made the function 2 LoC.
But it seems like a terrible idea to rely on the drag-and-drop functionality mutating the credits array to match the rendered index.
> fix(front): remove placeholder credit ordering

- apps/backend-e2e/src/admin.e2e-spec.ts
- apps/backend-e2e/src/session.e2e-spec.ts
- apps/backend-e2e/src/user.e2e-spec.ts
- apps/backend/src/app/dto/run/run-session.dto.ts
- apps/backend/src/app/modules/session/run/run-processor.class.spec.ts
- apps/backend/src/app/modules/session/run/run-processor.class.ts
- apps/backend/src/app/modules/session/run/run-session.interface.ts
- apps/backend/src/app/modules/session/run/run-session.service.ts
- apps/backend/src/app/modules/session/session.controller.ts
- apps/backend/src/app/modules/users/users.service.ts
- apps/frontend/src/app/services/data/maps.service.ts
- libs/constants/src/types/models/prisma-correspondence.ts
- libs/constants/src/types/queries/run-queries.model.ts
- libs/db/src/migrations/20250725142421_remove_run_sesssions/migration.sql
- libs/db/src/schema.prisma
Uses a plain JS map for run sessions in SQL. Discussed in meetings/Discord.
Based on top of https://github.com/momentum-mod/website/pull/1241, that needs merging before this.
> In memory run sessions

- apps/frontend/src/app/components/map-review/map-review-list.component.html
- apps/frontend/src/app/components/map-review/map-review-list.component.ts
Closes #1253
Not gonna bother trying to debug the inconsistent redirects. It should be fine now when looking at maps in submission when not logged in since those review components won't load.
> feat(front): hide map review form if not logged in

- apps/backend-e2e/src/maps.e2e-spec.ts
- apps/backend/src/app/config/config.interface.ts
- apps/backend/src/app/config/config.ts
- apps/backend/src/app/modules/discord/discord.service.ts
- apps/backend/src/app/modules/maps/map-status-notifications.service.ts
Now uses a forum channel instead of threads in a porting channel and fixes a bug where multiple notifications were sent if there are both ranked and unranked gamemodes in the same category. Also includes a small wording change.
> Even more map status notification changes

- apps/backend-e2e/src/admin.e2e-spec.ts
- apps/backend-e2e/src/maps.e2e-spec.ts
- apps/backend-e2e/src/user.e2e-spec.ts
- apps/backend/src/app/dto/queries/map-queries.dto.ts
- apps/backend/src/app/modules/maps/maps.service.ts
- apps/frontend/src/app/components/dropdown/dropdown.component.ts
- apps/frontend/src/app/components/n-state-button/n-state-button.component.ts
- apps/frontend/src/app/pages/maps/browsers/admin-maps-browser.component.html
- apps/frontend/src/app/pages/maps/browsers/admin-maps-browser.component.ts
- apps/frontend/src/app/pages/maps/browsers/map-browser.component.html
- apps/frontend/src/app/pages/maps/browsers/map-browser.component.ts
- apps/frontend/src/app/pages/maps/browsers/map-submission-browser.component.html
- apps/frontend/src/app/pages/maps/browsers/map-submission-browser.component.ts
- apps/frontend/src/app/pages/maps/browsers/user-maps-browser.component.html
- apps/frontend/src/app/pages/maps/browsers/user-maps-browser.component.ts
- apps/frontend/src/app/theme/styles.css
- apps/frontend/src/app/util/form-utils.util.ts
- libs/constants/src/maps/map-credit-name.map.ts
- libs/constants/src/types/queries/map-queries.model.ts
Part of #925 
Also
added VTG and KZ 1.6 to main browser
removed redundant map sort query option tests
Best to actually check out the branch, to see responsivity changes.
> Credit map browser filter (+ backend support), improved wrapping in map browsers

- libs/constants/src/types/models/models.ts
- libs/formats/zone/src/zone-util.ts
- libs/formats/zone/src/zone-validator.spec.ts
- libs/formats/zone/src/zone-validator.ts
This change was already made to the types file in the panorama repo, I didn't review the PR so didn't see that rio had modified types in the generated file directly.
> refactor(shared): update to zone types to allow for more missing fields

- apps/backend/src/app/modules/maps/maps.service.ts
Fixes this
Since user submissions query is not using submission query as parent now we need to explicitly add map submission data to the request as well
> fix(back): send map submission data when getting user submissions

- apps/backend/src/app/app.module.ts
- prod/backend/Dockerfile
We had some problems with running alpine before, but since we updated prisma and figured out the issue with wget on health check there is really no reason to use debian, and image becomes half as small
I also added a thing to write logs to stdout on prod while we are waiting for proper pino support for Sentry
> Use alpine for prod Docker container

- apps/frontend/src/app/interceptors/auth.interceptor.spec.ts
- apps/frontend/src/app/interceptors/auth.interceptor.ts
- apps/frontend/src/app/services/data/auth.service.ts
Improves overall experience on dashboard. Since out access tokens are very short lived, and refreshing logic only runs when there is a web request, and not on, for example, switching to another page, users are getting redirected to authentication page much more frequently.
Also fixes a "not found" error when opening a beta map link with expired access token. Since map pages can be accessed without authentication, validity of jwt token is not checked there, so the error returned to client is 403, rather then 401, which triggers refresh.
> Improve handling of expired access tokens

- libs/constants/src/consts/jwt.const.ts
15min expiry is absurdly low. 1day/1month seems pretty common practice for JWTs. If we were uber-concerned with security we probably wouldn't be using JWTs anyway.
> Increase JWT expiration times

- apps/frontend/src/app/components/gallery/gallery.component.html
Previous change doesn't work for bigger images
Before
After
> fix(front): better gallery styling

- apps/frontend/src/app/pages/maps/map-info/map-info.component.html
Show map creation date instead of when map was added to momentum
> fix(front): show map creation date by default

- apps/frontend/src/app/icons/packs/material-design-icons.icons.ts
- apps/frontend/src/app/side-menu.const.ts
Closes #1343
This pull request adds two important external links to the top of the main sidebar under a new "Navigation" section:
-   **Docs Home**: Links to `https://docs.momentum-mod.org` for easy access back to the documentation homepage.
-   **Main Site**: Links to `https://momentum-mod.org` to allow users to return to the main website.
This addresses the request in issue #1343 to improve site-wide navigation.
I was able to make the code changes but ran into some trouble getting the project running locally to provide a screenshot.
*(If you were able to run the project, drag your screenshot here. If not, you can just delete this section or leave it as is.)*
> enhancement(sidebar): Add docs and main site links
