server/README.md
server/config/config.js
server/config/express.js
server/config/sqlize.js
server/package.json
server/server.js
server/src/controllers/auth.js
server/src/controllers/users.js
server/src/models/db/user.js
server/src/models/user.js
server/src/routes/api/auth.js
server/src/routes/api/users.js
server/yarn.lock

And a test endpoint for game client auth we'll eventually do

Added sequelize

---

server/config/express.js
server/src/controllers/auth.js
server/src/controllers/users.js
server/src/models/auth.js
server/src/models/db/user.js
server/src/models/user.js
server/src/routes/api/users.js

Stores avatar URL now, updates and uses the info upon sign in

Update user model

---

.travis.yml
client/src/app/pages/dashboard/profile-card/profile-card.component.ts
client/src/app/pages/profile/profile-card/profile-card.component.ts

When we open pull requests, it'll require that your branch:
1. Have the latest master code,
2. Compiles in production mode,
3. Is linted (but pre-committing does this anyways, good to double check though)

Continuous Integration

---

client/src/app/@theme/styles/themes.scss
client/src/app/pages/dashboard/dashboard-menu.ts
client/src/app/pages/dashboard/maps/map-queue/map-queue.component.html
client/src/app/pages/dashboard/maps/uploads/uploads.component.html

created form for map submissions
changed background color of active tab

Modified map components

---

client/src/app/pages/dashboard/maps/map-queue/map-queue.component.html
client/src/app/pages/dashboard/maps/upload-status/upload-status.component.html
client/src/app/pages/dashboard/maps/uploads/uploads.component.html

Just minor changes that I wasn't happy with before.

Made changes to Maps

---

server/.gitignore
server/config/express.js
server/config/sqlize.js
server/package.json
server/public/maps/readme.txt
server/src/controllers/maps.js
server/src/models/db/map.js
server/src/models/map.js
server/src/models/user.js
server/src/routes/api/maps.js
server/yarn.lock

Will probably be replaced with CDN in the future?

Added map upload and download functionality to server

---

client/README.md
client/package.json
client/proxy.conf.json
server/config/express.js
server/package.json
server/yarn.lock

This removes the need to enable CORS on server and makes ajax routing on client easy :)

Added client proxy configuration

---

server/README.md
server/config/express.js
server/docs/swagger/auth.yaml
server/docs/swagger/definition.js
server/docs/swagger/errors.yaml
server/docs/swagger/maps.yaml
server/docs/swagger/users.yaml
server/package.json
server/yarn.lock

Added Swagger server API reference docs

---

client/src/app/pages/dashboard/maps/uploads/uploads.component.html

Removed and added components following Mockup.

Updated Map Upload Page

---

.travis.yml
client/karma.conf.js
server/config/config.js
server/setup-db.sh

Breaking things into stages, let's see how this goes

Trying a new CI layout for travis

---

client/src/app/@core/data/local-user.service.ts
client/src/app/@core/data/maps.service.spec.ts
client/src/app/@core/data/maps.service.ts
client/src/app/@core/data/users.service.ts
client/src/app/@core/guards/permission.guard.ts
client/src/app/@core/models/map-credit.model.ts
client/src/app/@core/models/map-upload-status.model.ts
client/src/app/@core/models/momentum-map.model.ts
client/src/app/@theme/styles/themes.scss
client/src/app/app-routing.module.ts
client/src/app/app.module.ts
client/src/app/pages/dashboard/dashboard-routing.module.ts
client/src/app/pages/dashboard/dashboard.component.ts
client/src/app/pages/dashboard/maps/map-routing.module.ts
client/src/app/pages/dashboard/maps/map.module.ts
client/src/app/pages/dashboard/maps/upload-status/map-status/map-status.component.html
client/src/app/pages/dashboard/maps/upload-status/map-status/map-status.component.spec.ts
client/src/app/pages/dashboard/maps/upload-status/map-status/map-status.component.ts
client/src/app/pages/dashboard/maps/upload-status/upload-status.component.html
client/src/app/pages/dashboard/maps/upload-status/upload-status.component.ts
client/src/app/pages/dashboard/maps/uploads/uploads.component.html
client/src/app/pages/dashboard/maps/uploads/uploads.component.ts
client/src/app/pages/dashboard/profile/profile-edit/profile-edit.component.html
client/src/app/pages/dashboard/profile/profile-edit/profile-edit.component.scss
client/src/app/pages/dashboard/profile/profile-edit/profile-edit.component.ts
client/src/app/pages/dashboard/profile/profile-info/profile-info.component.html
client/src/app/pages/dashboard/profile/profile-info/profile-info.component.ts
client/src/app/pages/dashboard/profile/user-profile.component.html

Reactive forms, map upload status layout, global toasts

---

client/src/app/@core/data/local-user.service.ts
client/src/app/pages/dashboard/maps/map.module.ts
client/src/app/pages/dashboard/maps/upload-status/map-status/map-status.component.html

Fix for toasts

---

client/src/app/@core/data/auth.service.ts
client/src/app/@core/data/local-user.service.ts
client/src/app/@core/data/users.service.ts

auth service, users service, local-user service

Added Code Comments

---

client/src/app/@core/data/activity.service.ts
client/src/app/@core/data/admin.service.ts

admin service and activity service

commented code

---

client/src/app/@core/data/activity.service.ts
client/src/app/@core/data/admin.service.ts
client/src/app/@core/data/local-user.service.ts
client/src/app/@core/data/maps.service.ts
client/src/app/@core/data/users.service.ts

activity, admin, local-user, and users services

added comments to code

---

client/src/app/@core/data/activity.service.spec.ts

Unit Test ActivityService

---

server/config/express.js
server/package.json
server/src/controllers/auth.js
server/src/models/run.js
server/src/models/user.js
server/src/routes/api/auth.js
server/yarn.lock

Accepts an auth request from the game, verifies the steam ID, generates a JWT for the game (which will eventually have specific perms), and sends it back to the client

Initial game auth implementation

---

client/src/app/pages/dashboard/profile/user-profile.component.html
client/src/app/pages/dashboard/profile/user-profile.component.scss

User Stats

---

client/src/app/pages/dashboard/maps/view-maps/view-maps.component.html

Fix browse maps header

---

server/src/models/db/run.js

Fix tickrate for run submission

---

client/src/app/@core/data/local-user.service.spec.ts
client/src/app/@core/data/maps.service.spec.ts
server/test/admin.js
server/test/auth.js
server/test/maps.js
server/test/user.js
server/test/users.js

Fixed local-user and maps service tests
Added/fixed server tests in user, users, maps, and auth

Fixes to server/service tests

---

server/config/sqlize.js

This is required for map favorites to work

Updated sequelize config

---

client/src/app/@core/models/momentum-map.model.ts
client/src/app/@theme/components/activity/activity-content/activity-content.component.ts
client/src/app/pages/dashboard/maps/map-info/map-info.component.ts
client/src/app/pages/dashboard/maps/map-library/map-library.component.html
client/src/app/pages/dashboard/maps/map-library/map-library.component.scss
client/src/app/pages/dashboard/maps/map-library/map-library.component.ts
client/src/app/pages/dashboard/maps/view-maps/map-list-item/map-list-item.component.html
client/src/app/pages/dashboard/maps/view-maps/map-list-item/map-list-item.component.scss
client/src/app/pages/dashboard/maps/view-maps/map-list-item/map-list-item.component.spec.ts
client/src/app/pages/dashboard/maps/view-maps/map-list-item/map-list-item.component.ts
client/src/app/pages/dashboard/maps/view-maps/view-maps.component.ts
server/config/sqlize.js
server/docs/swagger/maps.yaml
server/docs/swagger/user.yaml
server/src/controllers/admin.js
server/src/controllers/maps.js
server/src/controllers/user.js
server/src/models/map-library.js
server/src/models/map.js
server/test/maps.js

Added map upload activity generation & extra controls to map list item component

Some priority issue fixes

---

client/src/app/@theme/layouts/sample/sample.layout.ts
client/src/app/@theme/styles/pagination.scss
client/src/app/@theme/styles/styles.scss
client/src/app/pages/dashboard/admin/map-queue/map-queue.component.html
client/src/app/pages/dashboard/admin/map-queue/map-queue.component.scss
client/src/app/pages/dashboard/admin/map-queue/queued-map/queued-map.component.html
client/src/app/pages/dashboard/admin/map-queue/queued-map/queued-map.component.scss
client/src/app/pages/dashboard/admin/report-queue/report-queue.component.html
client/src/app/pages/dashboard/maps/map-list/map-list-item/map-list-item.component.html
client/src/app/pages/dashboard/maps/map-list/map-list-item/map-list-item.component.scss
client/src/app/pages/dashboard/maps/map-list/map-list.component.html
client/src/app/pages/dashboard/maps/map-list/map-list.component.scss
client/src/app/pages/dashboard/maps/map-list/map-list.component.ts
client/src/app/pages/dashboard/maps/upload-status/upload-status.component.html
client/src/app/pages/dashboard/profile/profile-credits/profile-credits.component.html
client/src/app/pages/dashboard/profile/profile-run-history/profile-run-history.component.html
server/docs/swagger/user.yaml
server/src/models/map-favorite.js
server/src/models/map-library.js
server/src/validations/user.js

Improves map list layout to be more responsive.
Registers map list page number in query parameters for better navigation.
Scrolls page to the top on map list page change.
Adds smooth scroll to supported browsers
Improves pagination styles to better fit in dark theme.
Fixes map search in library and favorites lists.

Map list improvements

---

client/src/app/@core/data/auth.service.ts
client/src/app/@core/data/local-user.service.ts
client/src/app/@core/guards/auth.guard.ts
client/src/app/pages/main/main-page.component.ts
server/public/index.html
server/src/controllers/auth.js
server/src/routes/auth/index.js

After successful login redirects to the page user originally wanted to access instead of the main dashboard page.

Redirect to referring page after login

---

client/src/app/@theme/components/report/report-button/report-button.component.html
client/src/app/@theme/components/report/report-button/report-button.component.scss
client/src/app/pages/dashboard/home/dashboard-home.component.html
client/src/app/pages/dashboard/home/dashboard-home.component.scss
client/src/app/pages/dashboard/home/home-stats/home-stats.component.html
client/src/app/pages/dashboard/home/home-stats/home-stats.component.scss
client/src/app/pages/dashboard/home/home-user-library/home-user-library.component.html
client/src/app/pages/dashboard/home/home-user-library/home-user-library.component.scss
client/src/app/pages/dashboard/home/home-user-maps/home-user-maps.component.html
client/src/app/pages/dashboard/home/home-user-maps/home-user-maps.component.scss
client/src/app/pages/dashboard/maps/map-info/map-info-credits/map-info-credits.component.html
client/src/app/pages/dashboard/maps/map-info/map-info-credits/map-info-credits.component.scss
client/src/app/pages/dashboard/maps/map-info/map-info-description/map-info-description.component.html
client/src/app/pages/dashboard/maps/map-info/map-info-description/map-info-description.component.scss
client/src/app/pages/dashboard/maps/map-info/map-info-stats/map-info-stats.component.html
client/src/app/pages/dashboard/maps/map-info/map-info-stats/map-info-stats.component.scss
client/src/app/pages/dashboard/maps/map-info/map-info.component.html
client/src/app/pages/dashboard/maps/map-info/map-info.component.scss
client/src/app/pages/dashboard/maps/map-info/map-leaderboard/map-leaderboard.component.html
client/src/app/pages/dashboard/maps/map-info/map-leaderboard/map-leaderboard.component.scss
client/src/app/pages/dashboard/maps/map-list/map-list.component.html
client/src/app/pages/dashboard/maps/map-list/map-list.component.ts
client/src/app/pages/dashboard/runs/run-info/run-info.component.html
client/src/app/pages/dashboard/runs/run-info/run-info.component.scss
client/src/app/pages/dashboard/stats/global-stats/global-stats-base/global-stats-base.component.html
client/src/app/pages/dashboard/stats/global-stats/global-stats-base/global-stats-base.component.scss
client/src/app/pages/dashboard/stats/global-stats/global-stats-maps/global-stats-maps.component.scss
client/src/app/pages/dashboard/stats/global-stats/global-stats-tops/global-stats-tops.component.html
client/src/app/pages/dashboard/stats/global-stats/global-stats-tops/global-stats-tops.component.scss

Improved map info, run info, global stats and home pages to be more responsive and a little bit more polished.
Fixed map list search's strange behavior when navigating pages.

Layout improvements

---

client/src/app/pages/dashboard/profile/profile-follow/profile-follow.component.ts
client/src/app/pages/dashboard/profile/profile-follow/profile-notify-edit/profile-notify-edit.component.html
client/src/app/pages/dashboard/profile/profile-follow/profile-notify-edit/profile-notify-edit.component.scss
client/src/app/pages/dashboard/profile/profile-follow/profile-notify-edit/profile-notify-edit.component.spec.ts
client/src/app/pages/dashboard/profile/profile-follow/profile-notify-edit/profile-notify-edit.component.ts
client/src/app/pages/dashboard/profile/profile.module.ts

Update content and small styling changes
Closes #313

Update user follow notification settings modal

---

server/src/models/db/user.js

Note that the TODO added in this PR will most likely be removed when working on issue #308

Fix avatar ban not being applied to user avatar image

---

client/src/app/pages/dashboard/maps/map-info/map-info-credits/map-info-credits.component.html
client/src/app/pages/dashboard/maps/map-info/map-info-credits/map-info-credits.component.spec.ts
client/src/app/pages/dashboard/maps/map-info/map-info.component.html
client/src/app/pages/dashboard/maps/map-list/map-list-item/map-list-item.component.html
client/src/app/pages/dashboard/profile/user-profile.component.html
client/src/app/pages/dashboard/profile/user-profile.component.ts

Also fix mouse cursor on some links

Add more links to navigate to user profiles

---

scripts/force_sync_db.js
server/src/models/run.js

Also fixed the force sync script to automatically exit upon completion

Allow RJ run submission

---

client/src/app/@core/data/maps.service.ts
client/src/app/pages/dashboard/maps/map-edit/map-edit.component.html
client/src/app/pages/dashboard/maps/map-edit/map-edit.component.scss
client/src/app/pages/dashboard/maps/map-edit/map-edit.component.spec.ts
client/src/app/pages/dashboard/maps/map-edit/map-edit.component.ts
client/src/app/pages/dashboard/maps/map.module.ts
server/docs/swagger/maps.yaml

Added map info (YouTube ID and map description) editing.
Added map credits editing and changes submitting.
Added some initial changes addressing images editing.
Added missing ```youtubeID``` property in the API docs.

Add map info and credits editing

---

server/src/controllers/ranks.js

This will show just their time if they did a run and their friends haven't, but honestly that's ok
Closes #364

Show the player's time alongside their friends' times

---

server/src/validations/user.js

Closes #389 
Gotta love one liners. Interesting how our old validation never caught something like this...

Fix user stats not showing for players

---

client/src/app/@core/models/map-type.model.ts
client/src/app/pages/dashboard/maps/upload-form/map-upload-form.component.html
client/src/app/pages/dashboard/maps/upload-form/map-upload-form.component.ts
server/src/models/map.js
server/src/models/run.js

Closes #383
Clarified the RJ gamemode to no longer be "RJ (Jump)", but rather "Rocket Jump".

Add the Stickyjump gamemode

---

client/src/app/pages/dashboard/maps/map-info/map-leaderboard/map-leaderboard.component.html
client/src/app/pages/dashboard/maps/map-info/map-leaderboard/map-leaderboard.component.ts

Allow users to filter top 10 times, around times, and friend's times

Filter leaderboard

---

client/src/app/pages/outgoing/outgoing.module.ts

Whitelist BASE_URL as an external site

---

client/src/app/@core/models/map-type.model.ts
client/src/app/pages/dashboard/maps/upload-form/map-upload-form.component.html
client/src/app/pages/dashboard/maps/upload-form/map-upload-form.component.ts
client/src/app/pages/main/gamemodes/gamemodes.component.ts
server/src/models/map.js
server/src/models/run.js

Closes #408 
Also added the rest of the gamemodes (as is part of 0.8.6's goal) so that we don't need to do anything other than main page info and allowing them in the run submission code.

Add Ahop Gamemode

---

env-vars.list
server/config/express.js
server/package.json

Implement Bunyan + Seq logging

---

server/src/models/run.js

Reject blatantly wrong stats

---

.github/workflows/frontendbuild.yml
src/ClientService/ClientApp/src/app/pages/main/nav/nav.component.ts

just very simple use of github actions building the frontend and uploading it as an artifact
Right now node_modules and the node install are cached between runs but no parts of the angular build are cached

Adding front end CI building

---

Frontend/src/app/@core/data/activity.service.spec.ts
Frontend/src/app/@core/data/activity.service.ts
Frontend/src/app/@core/data/admin.service.spec.ts
Frontend/src/app/@core/data/admin.service.ts
Frontend/src/app/@core/data/local-user.service.spec.ts
Frontend/src/app/@core/data/runs.service.spec.ts
Frontend/src/app/@core/data/users.service.spec.ts
Frontend/src/app/@core/data/users.service.ts
Frontend/src/app/@core/models/activity.model.ts
Frontend/src/app/@core/models/map-credit.model.ts
Frontend/src/app/@core/models/map-favorite.model.ts
Frontend/src/app/@core/models/map-library-entry.ts
Frontend/src/app/@core/models/momentum-map.model.ts
Frontend/src/app/@core/models/report.model.ts
Frontend/src/app/@core/models/run.model.ts
Frontend/src/app/@core/models/user-map-rank.model.ts
Frontend/src/app/@core/models/user.model.ts
Frontend/src/app/@theme/components/activity/activity-content/activity-content.component.spec.ts
Frontend/src/app/@theme/components/notification/notification.component.spec.ts
Frontend/src/app/pages/dashboard/community/community-activity/community-activity.component.spec.ts
Frontend/src/app/pages/dashboard/maps/map-edit/map-edit.component.spec.ts
Frontend/src/app/pages/dashboard/profile/profile-credits/profile-credits.component.spec.ts
Frontend/src/app/pages/dashboard/profile/profile-edit/profile-edit.component.ts
Frontend/src/app/pages/dashboard/profile/user-profile.component.ts

Seems okay for now. I'll have to double check it when the rewrite backend gets expanded more.

Changed UserID type from number to string on frontend for GUID support

---

client/src/app/pages/dashboard/dashboard-menu.ts
client/src/app/pages/main/footer/footer.component.html

Closes #479
Let me know if the order of things should be changed in either area.

Added links to forums on sidebar and homepage footer

---

client/src/app/pages/main/footer/footer.component.html

Closes #486
I used the font awesome icons the other links use.

Added Twitch link to main page footer

---

server/src/models/map.js
server/src/models/run.js

Also bumped the total upload max to 5 for the time being, with the proper fix being to exclude admins from the "map limit" for uploads.

Add Conc Map/Run Support

---

client/src/app/pages/main/gamemodes/gamemodes.component.scss
client/src/app/pages/main/header/header.component.scss
client/src/app/pages/main/nav/nav.component.scss

When viewing the main page on a small screen, there are a few issues which this PR fixes:
Before | After
:-:|:-:

Fix small responsive issues

---

client/src/app/@theme/components/header/header.component.scss
client/src/app/@theme/layouts/sample/sample.layout.scss
client/src/app/@theme/styles/styles.scss
client/src/app/pages/main/header/header.component.scss
client/src/app/pages/not-found/dashboard/not-found-dashboard.component.scss
client/src/app/pages/not-found/main/not-found-main.component.scss
client/src/app/pages/outgoing/outgoing.component.scss

A few more issues I've noticed, fixed here:
Before | After
:-:|:-:

Fix small issues #2

---

server/src/models/map-favorite.js
server/src/models/map-library.js

The first if check was failing when limit was 0, so it was always limiting to 20.

Fix Map Library + Favorites API Request

---

Dockerfile
client/src/app/@core/guards/auth.guard.ts
scripts/exports.needed
server/config/config.js
server/config/express.js
server/src/controllers/auth.js
server/src/models/db/user.js
server/src/models/map-image.js
server/src/models/map.js
server/src/models/run.js
server/src/routes/auth/index.js

`BASE_URL` gets joined by `API_URL`, `AUTH_URL`, and `CDN_URL` environment vars, making it easier to separate these out in the future as we cloud-ify more.
Updated the docker image to only generate the server now!

Update Backend URL Types

---

.github/workflows/dockerimage.yml
server/config/express.js
server/package.json
server/yarn.lock

Just using default config for now, might need to tweak some but not sure yet.
Closes #230

✨ Add helmet to backend

---

.github/workflows/dockerimage.yml

Need to change directory to the server folder now for it.

Fix backend docker image build action

---

client/src/app/@core/data/activity.service.ts
client/src/app/@core/data/local-user.service.ts

changes spelling in
- client/src/app/@core/data/activity.service.ts 
- client/src/app/@core/data/local-user.service.ts

Spelling fixes

---

README.md
client/src/app/@theme/layouts/sample/sample.layout.html
client/src/app/pages/main/about/about.component.html
client/src/app/pages/main/footer/footer.component.html

Replace all the existing discord URLs with our new custom one. Thanks Discord!

Update Discord URLs

---

client/src/app/pages/dashboard/maps/upload-form/map-upload-form.component.ts
server/src/models/map.js
server/src/models/run.js

Pretty basic change, also updated the prefixes and tickrates to match the modes properly now.

Add Defrag Run Uploading Support

---

server/src/@common/dto/map/map.dto.ts
server/src/@common/health/indicators/base-health.indicator.ts
server/src/app.module.ts
server/src/middlewares/http-logger.middleware.ts
server/src/modules/health/health.service.ts

The NestJS logger will be mostly what we need, for now. However we needed some extra steps for logging objects (just using `JSON.stringify` for now).
I've also added a HTTP middleware logger that will log all incoming requests (Ignores the `/auth` endpoints though, this my contain sensitive info)

🐛✨ - Logger Fixes and Enhancements

---

server/src/@common/filters/prisma-client-exception.filter.ts
server/src/main.ts

Adds a exception filter to main.ts, which appends error code and message to client whenever an exception is hit. Sends a generic error for database errors. Logs errors with same error code for easy tracing.

✨ - Error handling exception filtering

---

.github/ISSUE_TEMPLATE/0-feature.md
.github/ISSUE_TEMPLATE/1-bug.md
.github/ISSUE_TEMPLATE/2-question.md
.github/ISSUE_TEMPLATE/3-docs.md
.github/ISSUE_TEMPLATE/4-refactor.md
.github/ISSUE_TEMPLATE/5-devops.md

Closes https://github.com/momentum-mod/website/issues/578
copy paste casualty that apparently has just been happening for like a year I guess? i thought we already fixed this but maybe that was the discord bot repo or something.

Stop automatically assigning hona to every issue

---

server/tests/matchers.ts

Will now print if nested constraints are failing, really really useful

Dto matcher improvement

---

server/src/common/dto/query/map-queries.dto.ts
server/src/common/dto/query/run-queries.dto.ts
server/src/modules/admin/admin.controller.ts
server/src/modules/maps/maps.controller.ts
server/src/modules/maps/maps.module.ts
server/src/modules/maps/maps.service.ts
server/src/modules/runs/runs.controller.ts
server/src/modules/runs/runs.service.ts
server/src/modules/sentry/sentry.service.ts
server/src/modules/users/users.controller.ts
server/src/modules/users/users.service.ts
server/tests/e2e/maps.e2e-spec.ts
server/tests/e2e/runs.e2e-spec.ts

Just pulling in what I have atm

Endpoint Progress

---

server/src/modules/maps/map-library.service.ts
server/src/modules/maps/maps.module.ts
server/src/modules/user/user.controller.ts
server/src/modules/user/user.module.ts
server/tests/e2e/user.e2e-spec.ts

Previous PR branches got screwed up, re-doing PR.

feat: /user/maps/library/mapid/ GET

---

.github/workflows/test.yml
server/README.md

I am an IDIOT and didn't realise that Github runs the incoming changes to the workflow file so could have tested without merging. Balls!

fix: CI Linting workflow

---

server/prisma/schema.prisma
server/src/common/dto/query/map-queries.dto.ts
server/src/modules/admin/admin.controller.ts
server/src/modules/auth/auth.interfaces.ts
server/src/modules/maps/maps.controller.ts
server/src/modules/maps/maps.module.ts
server/src/modules/maps/maps.service.ts
server/src/modules/repo/maps-repo.service.ts
server/src/modules/repo/runs-repo.service.ts
server/src/modules/session/run/run-session.service.ts
server/src/modules/users/users.service.ts
server/tests/e2e/maps.e2e-spec.ts
server/tests/e2e/runs.e2e-spec.ts
server/tests/e2e/session.e2e-spec.ts

For some reason the DB doesn't record trackNum or trackZone, so they are implemented but there are no tests for them and there are warnings in the DTO and a comment as a note.

feat: GET /api/maps/{mapID}/ranks/{rankNumber}

---

docker-compose.override.yml
server/dev.Dockerfile

Workaround for openssl since prisma version < 4.8.0: https://github.com/prisma/prisma/issues/16553

Fix docker config

---

.github/workflows/dockerimage.yml
server/src/models/run.js

Cleans up the PR elgohr made automatically. I've run this on the Discord bot fine, most likely safe to upgrade directly but worth checking out after you merge.

Update publish docker GH action

---

server/src/models/map-favorite.js
server/src/models/map-library.js
server/src/models/map.js

Increase default maps getall limit to 300

---

.github/ISSUE_TEMPLATE/0-feature.md
.github/ISSUE_TEMPLATE/1-bug.md
.github/ISSUE_TEMPLATE/2-docs.md
.github/ISSUE_TEMPLATE/2-question.md
.github/ISSUE_TEMPLATE/3-refactor.md
.github/ISSUE_TEMPLATE/4-refactor.md
.github/ISSUE_TEMPLATE/5-devops.md
.gitignore
README.md

Finishing up the readme and nuking the fucking emojis from the issue templates

Misc chores

---

.github/workflows/test.yml

Tiny little fix, Afranche's PR was failing because of it. Confirmed it works on that branch already

ci: support checking out forked repos

---

apps/backend-e2e/src/admin.e2e-spec.ts
apps/backend-e2e/src/user.e2e-spec.ts
apps/backend/src/app/modules/admin/admin.controller.ts
apps/backend/src/app/modules/admin/admin.module.ts
apps/backend/src/app/modules/admin/admin.service.ts
apps/backend/src/app/modules/user/user.controller.ts
apps/backend/src/app/modules/users/users.service.ts
apps/frontend/src/app/components/components.module.ts
apps/frontend/src/app/components/delete-user-dialog/delete-user-dialog.component.html
apps/frontend/src/app/components/delete-user-dialog/delete-user-dialog.component.scss
apps/frontend/src/app/components/delete-user-dialog/delete-user-dialog.component.spec.ts
apps/frontend/src/app/components/delete-user-dialog/delete-user-dialog.component.ts
apps/frontend/src/app/pages/dashboard/profile/profile-edit/profile-edit.component.html
apps/frontend/src/app/pages/dashboard/profile/profile-edit/profile-edit.component.ts
apps/frontend/src/app/pages/dashboard/profile/user-profile.component.html
apps/frontend/src/app/pages/dashboard/profile/user-profile.component.ts
apps/frontend/src/assets/images/badges/BadgeDeleted.svg
libs/constants/src/role.enum.ts
libs/frontend/data/src/lib/local-user.service.ts

This PR closes issue https://github.com/momentum-mod/website/issues/292

Allow user deletion

---

apps/backend-e2e/src/users.e2e-spec.ts
apps/backend/src/app/modules/users/users.service.ts

fix(back): make /users GET search by alias case-insensitive

---

apps/backend-e2e/src/maps.e2e-spec.ts
apps/backend/src/app/modules/maps/map-review.service.ts
apps/backend/src/app/modules/maps/maps.controller.ts

feat(back): DELETE maps/:mapID/reviews/:reviewID endpoint

---

commitlint.config.js

I'm an idiot, misspelled this when trying to fix the other day.

Correct commitlint scope used by dependabot

---

apps/backend/src/app/dto/queries/user-queries.dto.ts
apps/backend/src/app/modules/users/users.service.spec.ts

test(back): adds tests for user creation in users-service

---

apps/backend/src/app/dto/user/admin-activity-dto.ts
apps/backend/src/app/modules/admin/admin-activity.service.ts
apps/backend/src/app/modules/admin/admin.service.ts
apps/frontend/src/app/components/accordion/accordion-item.component.ts
apps/frontend/src/app/components/accordion/accordion.component.ts
apps/frontend/src/app/components/index.ts
apps/frontend/src/app/icons/packs/material-design-icons.icons.ts
apps/frontend/src/app/pages/admin/admin-activity/admin-activity-entry/admin-activity-entry-header.component.ts
apps/frontend/src/app/pages/admin/admin-activity/admin-activity-entry/admin-activity-entry.component.ts
apps/frontend/src/app/pages/admin/admin-activity/admin-activity.component.html
apps/frontend/src/app/pages/admin/admin-activity/admin-activity.component.ts
apps/frontend/src/app/pages/admin/routes.ts
apps/frontend/src/app/pages/profile/profile.component.html
apps/frontend/src/app/pages/profile/profile.component.ts
apps/frontend/src/app/services/data/admin-activity.service.ts
apps/frontend/src/app/services/index.ts
apps/frontend/src/app/side-menu.const.ts
libs/constants/src/index.ts
libs/constants/src/maps/ban-names.map.ts
libs/constants/src/types/models/user/admin-activity.model.ts
libs/constants/src/types/queries/admin-queries.model.ts
libs/db/src/scripts/seed.ts

I'm sorry it took me so long to do that.

Admin Activity, Frontend part

---

apps/backend/src/app/modules/maps/maps.service.spec.ts
apps/frontend/src/app/app.component.css
apps/frontend/src/app/components/activity/activity.component.ts
apps/frontend/src/app/components/layout/header.component.css
apps/frontend/src/app/components/layout/header.component.html
apps/frontend/src/app/components/layout/header.component.ts
apps/frontend/src/app/components/layout/sidenav.component.html
apps/frontend/src/app/components/layout/sidenav.component.ts
apps/frontend/src/app/components/map-list/map-list-item.component.html
apps/frontend/src/app/components/map-list/map-list-item.component.ts
apps/frontend/src/app/components/map-review/map-review-list.component.ts
apps/frontend/src/app/components/map-review/map-review.component.html
apps/frontend/src/app/components/map-review/map-review.component.ts
apps/frontend/src/app/components/player-card/player-card.component.html
apps/frontend/src/app/components/player-card/player-card.component.ts
apps/frontend/src/app/guards/auth.guard.ts
apps/frontend/src/app/guards/role.guard.ts
apps/frontend/src/app/pages/home/home.component.ts
apps/frontend/src/app/pages/maps/browsers/map-browser.component.html
apps/frontend/src/app/pages/maps/browsers/map-browser.component.ts
apps/frontend/src/app/pages/maps/map-edit/map-edit.component.ts
apps/frontend/src/app/pages/maps/map-info/map-info.component.html
apps/frontend/src/app/pages/maps/map-info/map-info.component.ts
apps/frontend/src/app/pages/maps/submission-form/map-submission-form.component.ts
apps/frontend/src/app/pages/profile/profile-edit/profile-edit.component.ts
apps/frontend/src/app/pages/profile/profile-redirect.component.ts
apps/frontend/src/app/pages/profile/profile.component.ts
apps/frontend/src/app/services/data/auth.service.ts
apps/frontend/src/app/services/data/local-user.service.ts

Just a couple small things.
Generally I don't think we need to do hardcore mega-reactivity stuff where you avoid storing state on classes at all costs, but in the case of the local user service, using async pipes better to avoid storing stuff like `isLoggedIn` everywhere makes a lot of sense.

Misc tweaks for Gordi's login-less frontend

---

.github/workflows/dockerimage.yml
Dockerfile
apps/backend/src/app/config/config.interface.ts
apps/backend/src/app/config/config.ts
apps/backend/src/app/config/config.validation.ts
apps/backend/src/app/modules/auth/auth.controller.ts
apps/backend/src/app/modules/auth/auth.module.ts
apps/backend/src/app/modules/auth/steam/steam-openid.service.ts
apps/backend/src/main.ts
apps/frontend/src/app/pages/home/user-maps/home-user-maps.component.ts
docker-compose.override.yml
env.TEMPLATE
lint-staged.config.js

Supercedes #936
- Fixed .env file not being loaded by dev docker environment (thanks Gordi)
- Changed how URLs/domains are handled
- Disabled ESLint commit hook because it takes an absolutely absurd amount of time. CI checks and encouraging people to use the editor plugin is enough IMO.
- Docker Image publishing *hopefully* works, followed your recommendation Nick.
- Random faff

Fix production prep issues

---

apps/backend/src/app/config/config.interface.ts
apps/backend/src/app/config/config.ts
apps/backend/src/app/config/config.validation.ts
apps/backend/src/app/dto/map/map-image.dto.ts
apps/backend/src/app/dto/map/map-list-version.dto.ts
apps/backend/src/app/dto/map/map-review.dto.ts
apps/backend/src/app/dto/map/map-submission-version.dto.ts
apps/backend/src/app/dto/map/map.dto.ts
apps/backend/src/app/dto/run/leaderboard-run.dto.ts
docker-compose.test.yml
env.TEMPLATE
libs/db/src/scripts/seed.ts

Haven't tested E2E, quite likely to fail :)

Add dedicated CDN URL

---

.github/workflows/backend_docker_image.yml

build(back): expose sentry secrets to backend publihs workflow

---

apps/backend/src/app/app.module.ts
apps/backend/src/app/modules/sentry/sentry.module.ts

fix(back): actually pass new environment thing to sentry

---

apps/backend/src/app/modules/sentry/sentry.module.ts
apps/backend/webpack.config.js

SentryInterceptor should *hopefully* work now. Since this is TypeScript-specific DI stuff I can't test this by tweaking main.js in prod 🙃

Fix SentryInterceptor

---

apps/frontend/src/app/components/map-review/map-review.component.html
apps/frontend/src/app/pages/profile/profile.component.html

Closes #1005
Hides Steam profile button for deleted and placeholder profiles

Miscellaneous frontend fixes

---

server/package.json
server/yarn.lock

Should fix auth. Haven't tested locally.
https://github.com/DoctorMcKay/node-steam-appticket/issues/5

chore: bump steam-appticket to 2.0.0-beta.1

---

apps/backend/src/app/dto/map/map-zones.dto.ts
apps/frontend/src/app/pages/maps/map-edit/map-edit.component.html
libs/constants/src/types/models/models.ts
libs/formats/zone/src/zone-validator.ts

- Add allow bhop regions to zone model
- Remove .zon from zone file extension

Update zone models

---

prod/Dockerfile

build(meta): use debian-based image for prod Dockerfile

---

prod/Dockerfile

fix(prod): Fix adduser attributes for debian-based image

---

prod/Dockerfile

Damn it you npm and your weird hackery

---

apps/frontend/src/app/components/activity/activity.component.html
apps/frontend/src/app/components/activity/activity.component.ts
apps/frontend/src/app/components/layout/sidenav.component.css
apps/frontend/src/app/pages/admin/admin-activity/admin-activity-entry/admin-activity-entry.component.ts

1. Admin activity word wrap
Before
After
2. Sidenav animation
https://github.com/user-attachments/assets/092610ba-6f92-4e28-93f1-6b8c16a96252
3. Activities on user profiles now update when going to another profile

Misc frontend fixes

---

apps/backend-e2e/src/user.e2e-spec.ts
apps/backend/src/app/modules/user/user.controller.ts
apps/backend/src/app/modules/users/users.service.ts
apps/frontend/src/app/components/search/user-search.component.html
apps/frontend/src/app/pages/profile/profile.component.html
apps/frontend/src/app/pages/profile/profile.component.ts
apps/frontend/src/app/services/data/local-user.service.ts

Closes #897 
Created endpoints for steam friends and multiple user follows;
Added dialog modal to frontend, so the user can select multiple friends to follow;
Changed avatar size in search to match dialog avatar;

feat(shared): possibility to follow steam friends

---

apps/frontend/src/app/pages/profile/profile-edit/profile-edit.component.html
apps/frontend/src/app/pages/profile/profile-edit/profile-edit.component.ts

feat(front): allow assigning porter and map reviewer roles

---

apps/frontend/src/app/theme/styles.css
apps/frontend/src/index.html
apps/frontend/src/main.ts

fix(front): force frontend to always be in dark mode

---

apps/frontend/src/app/pages/maps/map-edit/map-edit.component.html
apps/frontend/src/app/pages/maps/map-edit/map-edit.component.ts
apps/frontend/src/app/pages/maps/map-info/map-info.component.html
apps/frontend/src/app/services/data/local-user.service.ts

fix(front): Show map edit button and page for reviewers

---

apps/frontend/src/app/components/map-forms/map-details-form/map-details-form.component.ts
apps/frontend/src/app/pages/maps/map-info/map-submission/map-submission.component.html
apps/frontend/src/app/pages/maps/map-info/map-submission/map-submission.component.ts
apps/frontend/src/app/util/download-zone-file.util.ts

More miscellaneous frontend fixes

---

apps/backend-e2e/src/maps-2.e2e-spec.ts
apps/backend/src/app/modules/maps/map-credits.service.ts
apps/frontend/src/app/pages/maps/map-edit/map-edit.component.ts

Fix wonky credits

---

apps/backend-e2e/src/admin.e2e-spec.ts
apps/backend-e2e/src/maps.e2e-spec.ts
apps/backend/src/app/app.module.ts
apps/backend/src/app/config/config.interface.ts
apps/backend/src/app/config/config.ts
apps/backend/src/app/modules/maps/map-list.service.spec.ts
apps/backend/src/app/modules/maps/map-list.service.ts
apps/backend/src/app/modules/maps/maps.service.ts
libs/constants/src/maps/map-tags.map.ts
package-lock.json
package.json

Make map lists generate on schedule, instead of map updates

---

apps/frontend/src/app/pages/maps/map-info/map-info.component.html

fix(front): decrease map info title maximum size

---

libs/constants/src/consts/limits.const.ts

Increase max maps in submission limit

---

apps/backend/src/app/modules/session/run/run-session.service.ts

Fixes an error where some replays would return 404. Previously it was deleting current PB run every time a new run was submitted, and saving a new one instead. Since we should only store PB runs, now it will call a function to save a new replay and delete a previous one only if a new run is a PB.

Only update a replay file if run is a PB

---

apps/backend-e2e/src/maps.e2e-spec.ts
apps/backend/src/app/dto/map/map-submission-placeholder.dto.ts
apps/frontend/src/app/components/map-forms/map-credits-selection/map-credits-selection.component.html

Closes #1155 
Now shows the Add button on placeholder alias >= 1 in map submission credit section.
Validation also passes on backend, by changing the DTO, added a test for it.
Should/can I unit/e2e test the frontend change as well?
Also regarding PR, is the convention to click the checkboxes below if they don't apply, as well?

Fix map submission placeholder length

---

apps/backend/src/app/dto/map/map-zones.dto.ts
libs/constants/src/types/models/models.ts

Overbounce regions

---

apps/backend/src/app/modules/session/run/run-processor.class.spec.ts
apps/backend/src/app/modules/session/run/run-processor.class.ts
libs/constants/src/types/models/models.ts

Fix run submissions with defragModifiers = 0 being treated as defragModifier runs

---

apps/backend/src/app/app.module.ts

Tmp impl of sentry logging to try out

feat(back): Sentry logging

---

apps/backend/src/app/modules/session/run/run-session.service.ts

Fixes issues 6481900963 on sentry

fix(back): move replay file upload outside the db transaction

---

libs/constants/src/maps/tick-intervals.map.ts

Fixes issue 6300531356 on Sentry

fix(back): change hl1 bhop tickrate to 100t

---

apps/frontend/src/app/components/map-review/map-review.component.html

Closes #1129 
Same fix as in previous PR.
Couldn't find any other occurrences where this was needed.

fix(front): map review double post

---

apps/backend/src/app/dto/map/map-zones.dto.ts

feat(back): add global cancel regions

---

prod/backend/Dockerfile

chore(ci): copy prisma engine to backend docker container

---

apps/backend/src/app/modules/session/run/run-session.service.ts

chore(back): add more logging to run related methods

---

.github/pull_request_template.md

docs(meta): fix PR template typo

---

apps/frontend/src/app/components/map-forms/map-image-selection/image-selection-item.class.ts
apps/frontend/src/app/pages/maps/map-edit/map-edit.component.ts

Fix frontend JS exceptions on maps with no images

---

apps/backend/src/app/modules/maps/leaderboard-handler.util.spec.ts
apps/backend/src/app/modules/maps/leaderboard-handler.util.ts
apps/frontend/src/app/components/map-forms/map-leaderboard-selection/map-leaderboard-selection.component.ts
apps/frontend/src/app/components/map-review/map-review-suggestions-form.component.ts
libs/constants/src/index.ts
libs/constants/src/sets/disabled-gamemodes.set.ts
libs/formats/zone/src/suggestions-validator.spec.ts
libs/formats/zone/src/suggestions-validator.ts
libs/formats/zone/src/zones.stub.ts

Closes #1252 
Based on https://github.com/momentum-mod/website/pull/1250

Add disabled gamemodes set for disabling MomKZ/KZT

---

apps/backend/src/app/validators/is-bigint.validator.ts
apps/frontend/src/app/components/search/user-search.component.ts

fix(front): steamID search indefinite wait

---

apps/frontend/src/app/pipes/timing.pipe.spec.ts
apps/frontend/src/app/pipes/timing.pipe.ts

Closes https://github.com/momentum-mod/website/issues/1286

fix(front): broken TimingPipe

---

README.md
apps/backend/src/app/dto/map/map-review-comment.dto.ts
apps/frontend/src/app/components/map-forms/map-credits-selection/map-credits-selection.component.ts
apps/frontend/src/app/components/map-forms/map-status-form/map-final-approval-form.component.ts
apps/frontend/src/app/components/map-review/map-review-form.component.html
apps/frontend/src/app/components/map-review/map-review-form.component.ts
apps/frontend/src/app/components/map-review/map-review.component.html
apps/frontend/src/app/components/map-review/map-review.component.ts
apps/frontend/src/app/pages/maps/map-info/map-info.component.html
apps/frontend/src/app/pages/maps/map-info/map-submission/map-submission.component.html
apps/frontend/src/app/pages/maps/submission-form/map-submission-form.component.ts

A whole bunch of small stuff I've discovered over time.
Notably, map porters missing to set the creation date (so I've removed the default value).
And review comment length not getting limited.
Tags taking too much space:
before (by Natan):
after:

Misc fixes/improvements

---

prod/backend/Dockerfile

Use debian slim image for prod

---

docker-compose.override.yml
docker-compose.test.yml
docker-compose.yml
libs/db/src/migrations/20250929200053_remove_rank_xp/migration.sql

Rank xp sql migration

---

apps/backend-e2e/src/user.e2e-spec.ts
apps/backend/src/app/dto/user/follow.dto.ts
apps/backend/src/app/modules/user/user.controller.ts
apps/frontend/src/app/services/data/local-user.service.ts
libs/constants/src/types/models/models.ts

Closes https://github.com/momentum-mod/website/security/code-scanning/43
Code scanning actually spotted something!

Fix potential vulnerability in unvalidated user follow input

---

apps/backend/src/app/modules/valkey/valkey.service.ts

If port is set to 0, host variable will be interpreted as unix socket path

feat(back): allow using unix sockets for valkey

---

scripts/src/seed.script.ts

Tiny thing I had sitting around

feat(scripts): generate approvedDate values in seed script

---

apps/frontend/src/app/components/map-forms/map-status-form/map-status-form.component.ts

fix(front): ignore tier if no suggestion for current leaderboard exists
